import { User, EmergencyReport, ResponseTeam, AuditLog, IncidentType, AdminReport, ResidentReport, ServiceSchedule, ResidentNotification, Hospital, Vehicle, VehicleStatus, RegistrationStatus, ReportSource } from './types';

export const mockUsers: User[] = [
  {
    id: 'USR001',
    firstName: 'Juan',
    lastName: 'Dela Cruz',
    email: 'juan.delacruz@email.com',
    contactNumber: '+63 917 123 4567',
    dateOfBirth: '1990-05-15',
    address: { houseNo: '123', street: 'Rizal St', barangay: 'Poblacion', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'National ID',
    role: 'admin',
    status: 'active',
    registeredAt: '2024-01-10T08:30:00Z',
  },
  {
    id: 'USR002',
    firstName: 'Maria',
    lastName: 'Santos',
    email: 'maria.santos@email.com',
    contactNumber: '+63 918 234 5678',
    dateOfBirth: '1988-08-22',
    address: { houseNo: '456', street: 'Mabini Ave', barangay: 'Tapuac', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'Driver\'s License',
    role: 'dispatcher',
    status: 'active',
    registeredAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'USR003',
    firstName: 'Pedro',
    lastName: 'Reyes',
    email: 'pedro.reyes@email.com',
    contactNumber: '+63 919 345 6789',
    dateOfBirth: '1995-03-10',
    address: { houseNo: '789', street: 'Quezon Blvd', barangay: 'Bonuan', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'National ID',
    role: 'dispatcher',
    status: 'active',
    registeredAt: '2024-02-01T09:15:00Z',
  },
  {
    id: 'USR004',
    firstName: 'Ana',
    lastName: 'Garcia',
    email: 'ana.garcia@email.com',
    contactNumber: '+63 920 456 7890',
    dateOfBirth: '1992-11-30',
    address: { houseNo: '321', street: 'Luna St', barangay: 'Pantal', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'PhilHealth ID',
    role: 'dispatcher',
    status: 'active',
    registeredAt: '2024-02-10T14:30:00Z',
  },
  {
    id: 'USR005',
    firstName: 'Carlos',
    lastName: 'Mendoza',
    email: 'carlos.mendoza@email.com',
    contactNumber: '+63 921 567 8901',
    dateOfBirth: '1985-07-08',
    address: { houseNo: '654', street: 'Burgos Ave', barangay: 'Mayombo', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'National ID',
    role: 'dispatcher',
    status: 'inactive',
    registeredAt: '2024-03-05T11:45:00Z',
  },
  {
    id: 'USR006',
    firstName: 'Rosa',
    lastName: 'Lim',
    email: 'rosa.lim@email.com',
    contactNumber: '+63 922 678 9012',
    dateOfBirth: '1998-01-25',
    address: { houseNo: '987', street: 'Del Pilar St', barangay: 'Salapingao', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'Voter\'s ID',
    role: 'dispatcher',
    status: 'suspended',
    registeredAt: '2024-03-15T16:20:00Z',
  },
  {
    id: 'USR007',
    firstName: 'Miguel',
    lastName: 'Torres',
    email: 'miguel.torres@email.com',
    contactNumber: '+63 923 789 0123',
    dateOfBirth: '1991-09-12',
    address: { houseNo: '147', street: 'Magsaysay St', barangay: 'Carael', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'National ID',
    role: 'dispatcher',
    status: 'active',
    registeredAt: '2024-04-01T07:00:00Z',
  },
  {
    id: 'USR008',
    firstName: 'Elena',
    lastName: 'Cruz',
    email: 'elena.cruz@email.com',
    contactNumber: '+63 924 890 1234',
    dateOfBirth: '1993-04-18',
    address: { houseNo: '258', street: 'Roxas Blvd', barangay: 'Poblacion', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'Driver\'s License',
    role: 'admin',
    status: 'active',
    registeredAt: '2024-04-20T13:10:00Z',
  },
  {
    id: 'USR009',
    firstName: 'Rafael',
    lastName: 'Navarro',
    email: 'rafael.navarro@email.com',
    contactNumber: '+63 925 901 2345',
    dateOfBirth: '1987-12-05',
    address: { houseNo: '369', street: 'Aguinaldo St', barangay: 'Bonuan', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'National ID',
    role: 'dispatcher',
    status: 'active',
    registeredAt: '2024-05-10T09:30:00Z',
  },
  {
    id: 'USR010',
    firstName: 'Lourdes',
    lastName: 'Villanueva',
    email: 'lourdes.villanueva@email.com',
    contactNumber: '+63 926 012 3456',
    dateOfBirth: '1994-06-28',
    address: { houseNo: '741', street: 'Jacinto St', barangay: 'Tapuac', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'PhilHealth ID',
    role: 'dispatcher',
    status: 'active',
    registeredAt: '2024-05-25T15:45:00Z',
  },
  {
    id: 'USR011',
    firstName: 'Fernando',
    lastName: 'Aquino',
    email: 'fernando.aquino@email.com',
    contactNumber: '+63 927 123 4560',
    dateOfBirth: '1989-02-14',
    address: { houseNo: '852', street: 'Rizal Ave', barangay: 'Poblacion', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'National ID',
    role: 'dispatcher',
    status: 'active',
    registeredAt: '2024-06-01T08:00:00Z',
  },
  {
    id: 'USR012',
    firstName: 'Isabella',
    lastName: 'Ramos',
    email: 'isabella.ramos@email.com',
    contactNumber: '+63 928 234 5671',
    dateOfBirth: '1996-10-03',
    address: { houseNo: '963', street: 'Mabini St', barangay: 'Mayombo', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'Voter\'s ID',
    role: 'dispatcher',
    status: 'inactive',
    registeredAt: '2024-06-15T10:30:00Z',
  },
  {
    id: 'USR013',
    firstName: 'Roberto',
    lastName: 'Guzman',
    email: 'roberto.guzman@email.com',
    contactNumber: '+63 929 345 6780',
    dateOfBirth: '1986-07-20',
    address: { houseNo: '111', street: 'Rizal Ave', barangay: 'Poblacion', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'National ID',
    role: 'driver/responder',
    status: 'active',
    registeredAt: '2024-07-01T08:00:00Z',
  },
  {
    id: 'USR014',
    firstName: 'Carmen',
    lastName: 'Rivera',
    email: 'carmen.rivera@email.com',
    contactNumber: '+63 930 456 7891',
    dateOfBirth: '1990-03-15',
    address: { houseNo: '222', street: 'Mabini Ave', barangay: 'Tapuac', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'Driver\'s License',
    role: 'driver/responder',
    status: 'active',
    registeredAt: '2024-07-05T09:30:00Z',
  },
  {
    id: 'USR015',
    firstName: 'Antonio',
    lastName: 'Reyes',
    email: 'antonio.reyes@email.com',
    contactNumber: '+63 931 567 8902',
    dateOfBirth: '1988-11-08',
    address: { houseNo: '333', street: 'Quezon Blvd', barangay: 'Bonuan', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'National ID',
    role: 'driver/responder',
    status: 'active',
    registeredAt: '2024-07-10T10:15:00Z',
  },
  {
    id: 'USR016',
    firstName: 'Diego',
    lastName: 'Castillo',
    email: 'diego.castillo@email.com',
    contactNumber: '+63 932 678 9013',
    dateOfBirth: '1993-05-22',
    address: { houseNo: '444', street: 'Luna St', barangay: 'Pantal', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'PhilHealth ID',
    role: 'driver/responder',
    status: 'inactive',
    registeredAt: '2024-07-15T14:00:00Z',
  },
];

export const mockIncidentTypes: IncidentType[] = [
  { id: 'IT001', name: 'Fire', description: 'Structural or wildfire incidents', priority: 'critical', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'IT002', name: 'Medical Emergency', description: 'Health-related emergencies', priority: 'high', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'IT003', name: 'Disaster', description: 'Natural disaster and calamity events', priority: 'high', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'IT004', name: 'Vehicular', description: 'Road traffic accidents', priority: 'medium', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'IT005', name: 'Trauma', description: 'Physical injury and trauma cases', priority: 'medium', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'IT006', name: 'Service', description: 'General service and assistance requests', priority: 'low', createdAt: '2024-01-01T00:00:00Z' },
];

export const mockReports: EmergencyReport[] = [
  {
    id: 'RPT001',
    type: 'Disaster',
    location: 'Barangay Poblacion, Dagupan',
    lat: 16.0433,
    lng: 120.3372,
    timestamp: '2026-03-04T06:30:00Z',
    status: 'pending',
    description: 'Knee-deep flooding reported along Rizal Street. Several families trapped in their homes.',
    reportedBy: { id: 'USR003', name: 'Pedro Reyes', contact: '+63 919 345 6789' },
    source: 'emergency-call',
    priority: 'high',
  },
  {
    id: 'RPT002',
    type: 'Fire',
    location: 'Barangay Tapuac, Dagupan',
    lat: 16.0389,
    lng: 120.3412,
    timestamp: '2026-03-04T07:15:00Z',
    status: 'dispatched',
    description: 'House fire reported at Mabini Avenue. Smoke visible from several blocks away.',
    reportedBy: { id: 'USR004', name: 'Ana Garcia', contact: '+63 920 456 7890' },
    source: 'mobile-app',
    assignedTeam: 'TM001',
    priority: 'critical',
    victimInfo: { name: 'Maria Santos', age: '35', sex: 'Female', address: '45 Mabini Ave, Tapuac', contact: '+63 918 234 5678' },
  },
  {
    id: 'RPT003',
    type: 'Vehicular',
    location: 'Quezon Boulevard, Dagupan',
    lat: 16.0456,
    lng: 120.3335,
    timestamp: '2026-03-04T08:45:00Z',
    status: 'acknowledged',
    description: 'Two-vehicle collision at intersection. Injuries reported.',
    reportedBy: { id: 'USR007', name: 'Miguel Torres', contact: '+63 923 789 0123' },
    source: 'emergency-call',
    assignedTeam: 'TM002',
    priority: 'medium',
    victimInfo: { name: 'Jose Magbanua', age: '45', sex: 'Male', address: 'Quezon Blvd, Dagupan', contact: '+63 935 000 1111' },
    witnessInfo: { name: 'Miguel Torres', contact: '+63 923 789 0123', statement: 'I saw the red car run the red light and hit the white van.' },
  },
  {
    id: 'RPT004',
    type: 'Medical Emergency',
    location: 'Barangay Bonuan, Dagupan',
    lat: 16.0512,
    lng: 120.3298,
    timestamp: '2026-03-04T09:20:00Z',
    status: 'resolved',
    description: 'Elderly resident experiencing chest pain. Needs immediate medical attention.',
    reportedBy: { id: 'USR009', name: 'Rafael Navarro', contact: '+63 925 901 2345' },
    source: 'mobile-app',
    assignedTeam: 'TM002',
    priority: 'high',
    victimInfo: { name: 'Lola Conching', age: '72', sex: 'Female', address: '12 Bonuan, Dagupan', contact: '+63 925 901 2345' },
  },
  {
    id: 'RPT005',
    type: 'Disaster',
    location: 'Dagupan City Proper',
    lat: 16.0427,
    lng: 120.3370,
    timestamp: '2026-03-03T14:00:00Z',
    status: 'dispatched',
    description: 'Typhoon signal raised. Strong winds and heavy rainfall expected.',
    reportedBy: { id: 'USR001', name: 'Juan Dela Cruz', contact: '+63 917 123 4567' },
    source: 'emergency-call',
    assignedTeam: 'TM001',
    priority: 'high',
  },
  {
    id: 'RPT006',
    type: 'Trauma',
    location: 'Barangay Salapingao, Dagupan',
    lat: 16.0375,
    lng: 120.3455,
    timestamp: '2026-03-03T16:30:00Z',
    status: 'pending',
    description: 'Minor landslide blocking road access. No casualties reported.',
    reportedBy: { id: 'USR006', name: 'Rosa Lim', contact: '+63 922 678 9012' },
    source: 'mobile-app',
    priority: 'medium',
  },
  {
    id: 'RPT007',
    type: 'Service',
    location: 'Barangay Mayombo, Dagupan',
    lat: 16.0400,
    lng: 120.3425,
    timestamp: '2026-03-03T20:00:00Z',
    status: 'resolved',
    description: 'Widespread power outage affecting entire barangay since 7PM.',
    reportedBy: { id: 'USR010', name: 'Lourdes Villanueva', contact: '+63 926 012 3456' },
    source: 'emergency-call',
    assignedTeam: 'TM003',
    priority: 'low',
  },
  {
    id: 'RPT008',
    type: 'Service',
    location: 'Bonuan Beach, Dagupan',
    lat: 16.0550,
    lng: 120.3250,
    timestamp: '2026-03-04T11:00:00Z',
    status: 'pending',
    description: 'Person swept away by strong currents at Bonuan Beach.',
    reportedBy: { id: 'USR011', name: 'Fernando Aquino', contact: '+63 927 123 4560' },
    source: 'emergency-call',
    priority: 'low',
  },
  {
    id: 'RPT009',
    type: 'Disaster',
    location: 'Barangay Pantal, Dagupan',
    lat: 16.0395,
    lng: 120.3380,
    timestamp: '2026-03-04T05:00:00Z',
    status: 'acknowledged',
    description: 'Waist-deep flood waters in Pantal area. Residents need evacuation.',
    reportedBy: { id: 'USR004', name: 'Ana Garcia', contact: '+63 920 456 7890' },
    source: 'mobile-app',
    assignedTeam: 'TM001',
    priority: 'high',
    witnessInfo: { name: 'Danilo Cruz', contact: '+63 934 222 3333', statement: 'The water rose very fast. Neighbors are stuck on their roofs.' },
  },
  {
    id: 'RPT010',
    type: 'Trauma',
    location: 'Barangay Carael, Dagupan',
    lat: 16.0470,
    lng: 120.3310,
    timestamp: '2026-03-04T12:30:00Z',
    status: 'invalid',
    description: 'Report of building leaning. Upon inspection, building is stable but needs repair.',
    reportedBy: { id: 'USR012', name: 'Isabella Ramos', contact: '+63 928 234 5671' },
    source: 'mobile-app',
    priority: 'medium',
  },
  {
    id: 'RPT011',
    type: 'Fire',
    location: 'Barangay Poblacion, Dagupan',
    lat: 16.0430,
    lng: 120.3365,
    timestamp: '2026-03-04T13:45:00Z',
    status: 'pending',
    description: 'Grass fire near residential area spreading quickly due to wind.',
    reportedBy: { id: 'USR003', name: 'Pedro Reyes', contact: '+63 919 345 6789' },
    source: 'mobile-app',
    priority: 'critical',
  },
  {
    id: 'RPT012',
    type: 'Disaster',
    location: 'Dagupan City',
    lat: 16.0440,
    lng: 120.3390,
    timestamp: '2026-03-04T02:00:00Z',
    status: 'resolved',
    description: 'Magnitude 4.5 earthquake felt. Minor damage to structures reported.',
    reportedBy: { id: 'USR001', name: 'Juan Dela Cruz', contact: '+63 917 123 4567' },
    source: 'emergency-call',
    assignedTeam: 'TM001',
    priority: 'high',
  },
];

export const mockResponseTeams: ResponseTeam[] = [
  {
    id: 'TM001',
    teamName: 'Team A',
    members: [
      { id: 'M001', name: 'Roberto Guzman', role: 'Driver/Responder', status: 'active' },
      { id: 'M002', name: 'Santiago Perez', role: 'Driver/Responder', status: 'active' },
    ],
    status: 'active',
    specializations: ['Flood Rescue', 'Fire Response'],
  },
  {
    id: 'TM002',
    teamName: 'Team B',
    members: [
      { id: 'M005', name: 'Carmen Rivera', role: 'Driver/Responder', status: 'active' },
      { id: 'M006', name: 'Teresa Flores', role: 'Driver/Responder', status: 'active' },
    ],
    status: 'active',
    specializations: ['Medical Emergency', 'First Aid'],
  },
  {
    id: 'TM003',
    teamName: 'Team C',
    members: [
      { id: 'M008', name: 'Antonio Reyes', role: 'Driver/Responder', status: 'active' },
      { id: 'M010', name: 'Francisco Diaz', role: 'Driver/Responder', status: 'active' },
    ],
    status: 'active',
    specializations: ['Structural Assessment', 'Utility Repair'],
  },
  {
    id: 'TM004',
    teamName: 'Team D',
    members: [
      { id: 'M011', name: 'Gregorio Magno', role: 'Driver/Responder', status: 'active' },
      { id: 'M012', name: 'Patricia Encarnacion', role: 'Driver/Responder', status: 'active' },
    ],
    status: 'inactive',
    specializations: ['Water Rescue', 'Search Operations'],
  },
  {
    id: 'TM005',
    teamName: 'Team E',
    members: [
      { id: 'M015', name: 'Ramon Espiritu', role: 'Driver/Responder', status: 'active' },
      { id: 'M016', name: 'Danilo Magbanua', role: 'Driver/Responder', status: 'active' },
    ],
    status: 'active',
    specializations: ['Fire Suppression', 'Hazmat Response'],
  },
];

export const mockAuditLogs: AuditLog[] = [
  { id: 'AL001', userId: 'USR001', userName: 'Juan Dela Cruz', action: 'LOGIN', details: 'Admin logged in successfully', timestamp: '2026-03-04T08:00:00Z', localId: 'ADM-001' },
  { id: 'AL002', userId: 'USR002', userName: 'Maria Santos', action: 'UPDATE_REPORT', details: 'Updated report RPT002 status to dispatched', timestamp: '2026-03-04T07:20:00Z', localId: 'DSP-002' },
  { id: 'AL005', userId: 'USR002', userName: 'Maria Santos', action: 'ASSIGN_TEAM', details: 'Assigned Team A to report RPT002', timestamp: '2026-03-04T07:25:00Z', localId: 'DSP-002' },
  { id: 'AL006', userId: 'USR001', userName: 'Juan Dela Cruz', action: 'UPDATE_USER', details: 'Suspended user Rosa Lim (USR006)', timestamp: '2026-03-02T11:00:00Z', localId: 'ADM-001' },
  { id: 'AL007', userId: 'USR001', userName: 'Juan Dela Cruz', action: 'CREATE_INCIDENT_TYPE', details: 'Created incident type: Trauma', timestamp: '2026-02-28T09:30:00Z', localId: 'ADM-001' },
  { id: 'AL008', userId: 'USR002', userName: 'Maria Santos', action: 'RESOLVE_REPORT', details: 'Resolved report RPT004', timestamp: '2026-03-04T10:30:00Z', localId: 'DSP-002' },
  { id: 'AL011', userId: 'USR002', userName: 'Maria Santos', action: 'LOGIN', details: 'Dispatcher logged in successfully', timestamp: '2026-03-04T06:30:00Z', localId: 'DSP-002' },
  { id: 'AL012', userId: 'USR001', userName: 'Juan Dela Cruz', action: 'CREATE_USER', details: 'Created new user account for Fernando Aquino', timestamp: '2026-06-01T08:00:00Z', localId: 'ADM-001' },
];

// Resident users
export const mockResidents: User[] = [
  {
    id: 'RES001',
    firstName: 'Ligaya',
    lastName: 'Santos',
    middleInitial: 'R',
    sex: 'Female',
    email: 'ligaya.santos@email.com',
    contactNumber: '+63 933 111 2222',
    dateOfBirth: '1985-04-12',
    address: { houseNo: '55', street: 'Rizal St', barangay: 'Poblacion', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'National ID',
    role: 'resident',
    status: 'active',
    registeredAt: '2025-01-15T08:00:00Z',
    registrationStatus: 'accepted',
  },
  {
    id: 'RES002',
    firstName: 'Danilo',
    lastName: 'Cruz',
    middleInitial: 'A',
    sex: 'Male',
    email: 'danilo.cruz@email.com',
    contactNumber: '+63 934 222 3333',
    dateOfBirth: '1978-08-25',
    address: { houseNo: '102', street: 'Mabini Ave', barangay: 'Tapuac', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'Voter\'s ID',
    role: 'resident',
    status: 'active',
    registeredAt: '2025-02-01T10:00:00Z',
    registrationStatus: 'accepted',
  },
  {
    id: 'RES003',
    firstName: 'Rosario',
    lastName: 'Mendoza',
    middleInitial: 'T',
    sex: 'Female',
    email: 'rosario.mendoza@email.com',
    contactNumber: '+63 935 333 4444',
    dateOfBirth: '1992-12-05',
    address: { houseNo: '78', street: 'Quezon Blvd', barangay: 'Bonuan', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'PhilHealth ID',
    role: 'resident',
    status: 'active',
    registeredAt: '2025-03-10T09:30:00Z',
    registrationStatus: 'accepted',
  },
  {
    id: 'RES004',
    firstName: 'Ernesto',
    lastName: 'Villanueva',
    middleInitial: 'G',
    sex: 'Male',
    email: 'ernesto.villanueva@email.com',
    contactNumber: '+63 936 444 5555',
    dateOfBirth: '1970-06-18',
    address: { houseNo: '230', street: 'Luna St', barangay: 'Pantal', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'National ID',
    role: 'resident',
    status: 'active',
    registeredAt: '2025-04-05T14:00:00Z',
    registrationStatus: 'accepted',
  },
  {
    id: 'RES005',
    firstName: 'Carla',
    lastName: 'Reyes',
    middleInitial: 'M',
    sex: 'Female',
    email: 'carla.reyes@email.com',
    contactNumber: '+63 937 555 6666',
    dateOfBirth: '1990-03-14',
    address: { houseNo: '45', street: 'Burgos Ave', barangay: 'Mayombo', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'National ID',
    role: 'resident',
    status: 'inactive',
    registeredAt: '2026-03-01T10:00:00Z',
    registrationStatus: 'pending',
  },
  {
    id: 'RES006',
    firstName: 'Mark',
    lastName: 'Aquino',
    middleInitial: 'J',
    sex: 'Male',
    email: 'mark.aquino@email.com',
    contactNumber: '+63 938 666 7777',
    dateOfBirth: '1985-07-22',
    address: { houseNo: '88', street: 'Rizal St', barangay: 'Poblacion', city: 'Dagupan', province: 'Pangasinan' },
    idType: "Driver's License",
    role: 'resident',
    status: 'inactive',
    registeredAt: '2026-03-02T14:00:00Z',
    registrationStatus: 'pending',
  },
  {
    id: 'RES007',
    firstName: 'Grace',
    lastName: 'Flores',
    middleInitial: 'L',
    sex: 'Female',
    email: 'grace.flores@email.com',
    contactNumber: '+63 939 777 8888',
    dateOfBirth: '1995-11-08',
    address: { houseNo: '120', street: 'Quezon Blvd', barangay: 'Bonuan', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'PhilHealth ID',
    role: 'resident',
    status: 'inactive',
    registeredAt: '2026-03-03T09:00:00Z',
    registrationStatus: 'pending',
  },
  {
    id: 'RES008',
    firstName: 'Ricky',
    lastName: 'Diaz',
    middleInitial: 'P',
    sex: 'Male',
    email: 'ricky.diaz@email.com',
    contactNumber: '+63 940 888 9999',
    dateOfBirth: '1982-01-30',
    address: { houseNo: '200', street: 'Mabini Ave', barangay: 'Tapuac', city: 'Dagupan', province: 'Pangasinan' },
    idType: "Voter's ID",
    role: 'resident',
    status: 'inactive',
    registeredAt: '2026-02-15T08:00:00Z',
    registrationStatus: 'declined',
  },
  {
    id: 'RES009',
    firstName: 'Lorna',
    lastName: 'Vera',
    middleInitial: 'S',
    sex: 'Female',
    email: 'lorna.vera@email.com',
    contactNumber: '+63 941 999 0000',
    dateOfBirth: '1975-05-17',
    address: { houseNo: '310', street: 'Luna St', barangay: 'Pantal', city: 'Dagupan', province: 'Pangasinan' },
    idType: 'National ID',
    role: 'resident',
    status: 'inactive',
    registeredAt: '2026-02-20T11:00:00Z',
    registrationStatus: 'declined',
  },
];

// Resident Reports
export const mockResidentReports: ResidentReport[] = [
  {
    id: 'RR001',
    residentId: 'RES001',
    residentName: 'Ligaya Santos',
    type: 'Disaster',
    reporterType: 'victim',
    location: 'Rizal St, Poblacion, Dagupan',
    lat: 16.0433,
    lng: 120.3372,
    timestamp: '2026-03-04T06:30:00Z',
    status: 'dispatched',
    description: 'Knee-deep flooding in our area. Need immediate evacuation.',
    assignedTeam: 'TM001',
    priority: 'high',
  },
  {
    id: 'RR002',
    residentId: 'RES002',
    residentName: 'Danilo Cruz',
    type: 'Fire',
    reporterType: 'witness',
    location: 'Mabini Ave, Tapuac, Dagupan',
    lat: 16.0389,
    lng: 120.3412,
    timestamp: '2026-03-04T07:15:00Z',
    status: 'pending',
    description: 'House fire visible from my location. Heavy smoke.',
    priority: 'critical',
  },
  {
    id: 'RR003',
    residentId: 'RES003',
    residentName: 'Rosario Mendoza',
    type: 'Medical Emergency',
    reporterType: 'victim',
    location: 'Quezon Blvd, Bonuan, Dagupan',
    lat: 16.0512,
    lng: 120.3298,
    timestamp: '2026-03-04T09:20:00Z',
    status: 'resolved',
    description: 'My neighbor is experiencing severe chest pain.',
    assignedTeam: 'TM002',
    priority: 'high',
  },
  {
    id: 'RR004',
    residentId: 'RES004',
    residentName: 'Ernesto Villanueva',
    type: 'Vehicular',
    reporterType: 'witness',
    location: 'Luna St, Pantal, Dagupan',
    lat: 16.0395,
    lng: 120.3380,
    timestamp: '2026-03-04T11:00:00Z',
    status: 'acknowledged',
    description: 'Two cars collided at the intersection near our street.',
    assignedTeam: 'TM003',
    priority: 'medium',
  },
  {
    id: 'RR005',
    residentId: 'RES001',
    residentName: 'Ligaya Santos',
    type: 'Service',
    reporterType: 'victim',
    location: 'Rizal St, Poblacion, Dagupan',
    lat: 16.0430,
    lng: 120.3365,
    timestamp: '2026-03-03T15:00:00Z',
    status: 'resolved',
    description: 'Power outage in our entire block since 2PM.',
    assignedTeam: 'TM003',
    priority: 'low',
  },
];

// Service Schedules
export const mockServiceSchedules: ServiceSchedule[] = [
  {
    id: 'SCH001',
    residentId: 'RES001',
    residentName: 'Ligaya Santos',
    residentContact: '+63 933 111 2222',
    serviceType: 'Medical Transport',
    preferredDate: '2026-03-10',
    preferredTime: '08:00 AM',
    address: '55 Rizal St, Poblacion, Dagupan',
    notes: 'Wheelchair transport needed for hospital appointment',
    status: 'confirmed',
    createdAt: '2026-03-04T10:00:00Z',
    acknowledgedBy: 'Maria Santos',
    acknowledgedAt: '2026-03-04T10:30:00Z',
  },
  {
    id: 'SCH002',
    residentId: 'RES002',
    residentName: 'Danilo Cruz',
    residentContact: '+63 934 222 3333',
    serviceType: 'Relief Goods Delivery',
    preferredDate: '2026-03-08',
    preferredTime: '10:00 AM',
    address: '102 Mabini Ave, Tapuac, Dagupan',
    notes: 'Family of 5 affected by flooding, need food and water',
    status: 'pending',
    createdAt: '2026-03-04T11:00:00Z',
  },
  {
    id: 'SCH003',
    residentId: 'RES003',
    residentName: 'Rosario Mendoza',
    residentContact: '+63 935 333 4444',
    serviceType: 'Evacuation Assistance',
    preferredDate: '2026-03-06',
    preferredTime: '06:00 AM',
    address: '78 Quezon Blvd, Bonuan, Dagupan',
    notes: 'Need help evacuating elderly mother from flood-prone area',
    status: 'confirmed',
    createdAt: '2026-03-04T08:00:00Z',
    acknowledgedBy: 'Pedro Reyes',
    acknowledgedAt: '2026-03-04T08:15:00Z',
  },
  {
    id: 'SCH004',
    residentId: 'RES004',
    residentName: 'Ernesto Villanueva',
    residentContact: '+63 936 444 5555',
    serviceType: 'Medical Transport',
    preferredDate: '2026-03-12',
    preferredTime: '09:00 AM',
    address: '230 Luna St, Pantal, Dagupan',
    notes: 'Regular dialysis appointment transport',
    status: 'pending',
    createdAt: '2026-03-04T14:00:00Z',
  },
  {
    id: 'SCH005',
    residentId: 'RES001',
    residentName: 'Ligaya Santos',
    residentContact: '+63 933 111 2222',
    serviceType: 'Medical Transport',
    preferredDate: '2026-03-15',
    preferredTime: '07:00 AM',
    address: '55 Rizal St, Poblacion, Dagupan',
    notes: 'Follow-up checkup at Region 1 Medical Center',
    status: 'pending',
    createdAt: '2026-03-05T08:00:00Z',
  },
  {
    id: 'SCH006',
    residentId: 'RES005',
    residentName: 'Carla Reyes',
    residentContact: '+63 937 555 6666',
    serviceType: 'Relief Goods Delivery',
    preferredDate: '2026-03-07',
    preferredTime: '02:00 PM',
    address: '45 Burgos Ave, Mayombo, Dagupan',
    notes: 'Need basic supplies after house fire damage',
    status: 'pending',
    createdAt: '2026-03-05T09:30:00Z',
  },
  {
    id: 'SCH007',
    residentId: 'RES006',
    residentName: 'Mark Aquino',
    residentContact: '+63 938 666 7777',
    serviceType: 'Evacuation Assistance',
    preferredDate: '2026-03-09',
    preferredTime: '05:00 AM',
    address: '88 Rizal St, Poblacion, Dagupan',
    notes: 'Pre-emptive evacuation due to typhoon warning',
    status: 'acknowledged',
    createdAt: '2026-03-05T10:00:00Z',
    acknowledgedBy: 'Maria Santos',
    acknowledgedAt: '2026-03-05T10:20:00Z',
  },
  {
    id: 'SCH008',
    residentId: 'RES002',
    residentName: 'Danilo Cruz',
    residentContact: '+63 934 222 3333',
    serviceType: 'Medical Transport',
    preferredDate: '2026-03-11',
    preferredTime: '11:00 AM',
    address: '102 Mabini Ave, Tapuac, Dagupan',
    notes: 'Laboratory tests at Dagupan City Hospital',
    status: 'declined',
    createdAt: '2026-03-04T16:00:00Z',
    declineReason: 'No available vehicle on the requested date. Please reschedule to March 13 or later.',
  },
];

// Resident Notifications
export const mockResidentNotifications: ResidentNotification[] = [
  {
    id: 'RN001',
    residentId: 'RES001',
    title: 'Schedule Confirmed',
    message: 'Your Medical Transport schedule for March 10, 2026 at 8:00 AM has been confirmed by Dispatcher Maria Santos.',
    type: 'schedule_confirmed',
    read: false,
    timestamp: '2026-03-04T10:30:00Z',
    relatedId: 'SCH001',
  },
  {
    id: 'RN002',
    residentId: 'RES001',
    title: 'Report Update',
    message: 'Your disaster report has been dispatched. Team A is on the way.',
    type: 'report_update',
    read: true,
    timestamp: '2026-03-04T06:45:00Z',
    relatedId: 'RR001',
  },
  {
    id: 'RN003',
    residentId: 'RES002',
    title: 'Report Received',
    message: 'Your fire report has been received and is being processed.',
    type: 'report_update',
    read: false,
    timestamp: '2026-03-04T07:16:00Z',
    relatedId: 'RR002',
  },
  {
    id: 'RN004',
    residentId: 'RES003',
    title: 'Schedule Confirmed',
    message: 'Your Evacuation Assistance schedule for March 6, 2026 has been confirmed by Dispatcher Pedro Reyes.',
    type: 'schedule_confirmed',
    read: false,
    timestamp: '2026-03-04T08:15:00Z',
    relatedId: 'SCH003',
  },
  {
    id: 'RN005',
    residentId: 'RES004',
    title: 'Report Acknowledged',
    message: 'Your vehicular accident report has been acknowledged. Team C has been assigned.',
    type: 'report_update',
    read: true,
    timestamp: '2026-03-04T11:05:00Z',
    relatedId: 'RR004',
  },
];

// Hospitals
export const mockHospitals: Hospital[] = [
  {
    id: 'HOSP001',
    name: 'Region 1 Medical Center',
    address: 'Arellano St, Dagupan City',
    lat: 16.0439,
    lng: 120.3355,
    distance: 1.2,
    specialization: ['Trauma', 'Emergency', 'Surgery', 'Pediatrics'],
    availableBeds: 15,
    contactNumber: '+63 75 522 8151',
    estimatedArrivalMinutes: 8,
  },
  {
    id: 'HOSP002',
    name: 'Dagupan City Hospital',
    address: 'Dagupan City Proper',
    lat: 16.0420,
    lng: 120.3400,
    distance: 0.8,
    specialization: ['General', 'Emergency', 'OB-Gyne'],
    availableBeds: 8,
    contactNumber: '+63 75 522 3100',
    estimatedArrivalMinutes: 5,
  },
  {
    id: 'HOSP003',
    name: 'Pangasinan Provincial Hospital',
    address: 'San Carlos City, Pangasinan',
    lat: 15.9280,
    lng: 120.3480,
    distance: 12.5,
    specialization: ['General', 'Surgery', 'Pediatrics', 'OB-Gyne'],
    availableBeds: 25,
    contactNumber: '+63 75 532 2100',
    estimatedArrivalMinutes: 25,
  },
];

// Shift data
export const mockShifts: { teamId: string; teamName: string; shifts: { id: string; startTime: string; endTime: string; status: string; members: { id: string; name: string; role: string }[] }[] }[] = [
  {
    teamId: 'TM001',
    teamName: 'Team A',
    shifts: [
      { id: 'SH001', startTime: '06:00 AM', endTime: '02:00 PM', status: 'on-shift', members: [{ id: 'M001', name: 'Roberto Guzman', role: 'Driver' }, { id: 'M002', name: 'Santiago Perez', role: 'Responder' }] },
      { id: 'SH003', startTime: '10:00 PM', endTime: '06:00 AM', status: 'off-shift', members: [{ id: 'M001', name: 'Roberto Guzman', role: 'Driver' }, { id: 'M002', name: 'Santiago Perez', role: 'Responder' }] },
    ],
  },
  {
    teamId: 'TM002',
    teamName: 'Team B',
    shifts: [
      { id: 'SH004', startTime: '06:00 AM', endTime: '02:00 PM', status: 'on-shift', members: [{ id: 'M005', name: 'Carmen Rivera', role: 'Driver' }, { id: 'M006', name: 'Teresa Flores', role: 'Responder' }] },
      { id: 'SH005', startTime: '02:00 PM', endTime: '10:00 PM', status: 'off-shift', members: [{ id: 'M005', name: 'Carmen Rivera', role: 'Driver' }, { id: 'M006', name: 'Teresa Flores', role: 'Responder' }] },
    ],
  },
  {
    teamId: 'TM003',
    teamName: 'Team C',
    shifts: [
      { id: 'SH006', startTime: '06:00 AM', endTime: '06:00 PM', status: 'on-shift', members: [{ id: 'M008', name: 'Antonio Reyes', role: 'Driver' }, { id: 'M010', name: 'Francisco Diaz', role: 'Responder' }] },
    ],
  },
  {
    teamId: 'TM005',
    teamName: 'Team E',
    shifts: [
      { id: 'SH007', startTime: '08:00 AM', endTime: '08:00 PM', status: 'on-shift', members: [{ id: 'M015', name: 'Ramon Espiritu', role: 'Driver' }, { id: 'M016', name: 'Danilo Magbanua', role: 'Responder' }] },
    ],
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: 'VH001',
    teamId: 'TM001',
    teamName: 'Team A',
    vehicleType: 'rescue-van',
    plateNumber: 'ABX 1234',
    lat: 16.0410,
    lng: 120.3390,
    status: 'en-route',
    speed: 45,
    heading: 180,
    assignedReportId: 'RPT001',
    lastUpdated: '2026-03-04T08:30:00Z',
  },
  {
    id: 'VH002',
    teamId: 'TM002',
    teamName: 'Team B',
    vehicleType: 'ambulance',
    plateNumber: 'CDF 5678',
    lat: 16.0389,
    lng: 120.3412,
    status: 'on-scene',
    speed: 0,
    heading: 0,
    assignedReportId: 'RPT002',
    lastUpdated: '2026-03-04T07:45:00Z',
  },
  {
    id: 'VH003',
    teamId: 'TM003',
    teamName: 'Team C',
    vehicleType: 'utility-truck',
    plateNumber: 'GHI 9012',
    lat: 16.0460,
    lng: 120.3350,
    status: 'returning',
    speed: 35,
    heading: 90,
    lastUpdated: '2026-03-04T08:20:00Z',
  },
  {
    id: 'VH004',
    teamId: 'TM004',
    teamName: 'Team D',
    vehicleType: 'rescue-van',
    plateNumber: 'JKL 3456',
    lat: 16.0520,
    lng: 120.3270,
    status: 'offline',
    speed: 0,
    heading: 0,
    lastUpdated: '2026-03-04T06:00:00Z',
  },
  {
    id: 'VH005',
    teamId: 'TM005',
    teamName: 'Team E',
    vehicleType: 'fire-truck',
    plateNumber: 'MNO 7890',
    lat: 16.0430,
    lng: 120.3365,
    status: 'en-route',
    speed: 50,
    heading: 270,
    assignedReportId: 'RPT011',
    lastUpdated: '2026-03-04T08:35:00Z',
  },
  {
    id: 'VH006',
    teamId: 'TM001',
    teamName: 'Team A',
    vehicleType: 'ambulance',
    plateNumber: 'ABX 5678',
    lat: 16.0395,
    lng: 120.3380,
    status: 'on-scene',
    speed: 0,
    heading: 0,
    assignedReportId: 'RPT009',
    lastUpdated: '2026-03-04T08:15:00Z',
  },
  {
    id: 'VH007',
    teamId: 'TM002',
    teamName: 'Team B',
    vehicleType: 'ambulance',
    plateNumber: 'CDF 1234',
    lat: 16.0445,
    lng: 120.3335,
    status: 'available',
    speed: 0,
    heading: 0,
    lastUpdated: '2026-03-04T08:25:00Z',
  },
  {
    id: 'VH008',
    teamId: 'TM005',
    teamName: 'Team E',
    vehicleType: 'fire-truck',
    plateNumber: 'MNO 1234',
    lat: 16.0427,
    lng: 120.3370,
    status: 'on-scene',
    speed: 0,
    heading: 0,
    assignedReportId: 'RPT005',
    lastUpdated: '2026-03-04T07:30:00Z',
  },
];

export const mockHeatmapData = [
  { lat: 16.0433, lng: 120.3372, intensity: 0.9, type: 'Disaster' },
  { lat: 16.0389, lng: 120.3412, intensity: 0.8, type: 'Fire' },
  { lat: 16.0456, lng: 120.3335, intensity: 0.5, type: 'Vehicular' },
  { lat: 16.0512, lng: 120.3298, intensity: 0.6, type: 'Medical Emergency' },
  { lat: 16.0427, lng: 120.3370, intensity: 0.95, type: 'Disaster' },
  { lat: 16.0375, lng: 120.3455, intensity: 0.7, type: 'Trauma' },
  { lat: 16.0400, lng: 120.3425, intensity: 0.3, type: 'Service' },
  { lat: 16.0550, lng: 120.3250, intensity: 0.85, type: 'Service' },
  { lat: 16.0395, lng: 120.3380, intensity: 0.75, type: 'Disaster' },
  { lat: 16.0430, lng: 120.3365, intensity: 0.7, type: 'Fire' },
  { lat: 16.0440, lng: 120.3390, intensity: 0.65, type: 'Disaster' },
  { lat: 16.0470, lng: 120.3310, intensity: 0.4, type: 'Trauma' },
];

// Stats
export const adminDashboardStats = {
  totalUsers: 1248,
  activeReports: 23,
  pendingApprovals: 8,
  reportsResolved24h: 15,
  reportsToday: 12,
  avgResolutionTime: '2.4h',
  resolutionRate7d: 87,
};

export const reportsByType = [
  { type: 'Fire', count: 5, color: '#ef4444' },
  { type: 'Medical Emergency', count: 4, color: '#22c55e' },
  { type: 'Disaster', count: 8, color: '#3b82f6' },
  { type: 'Vehicular', count: 3, color: '#f59e0b' },
  { type: 'Trauma', count: 2, color: '#ec4899' },
  { type: 'Service', count: 2, color: '#6b7280' },
];

export const recentActivity = [
  { id: 1, action: 'New disaster report filed', user: 'Pedro Reyes', time: '5 min ago', type: 'report' },
  { id: 2, action: 'Team A dispatched', user: 'Maria Santos', time: '12 min ago', type: 'dispatch' },
  { id: 3, action: 'Report RPT004 resolved', user: 'Maria Santos', time: '30 min ago', type: 'resolve' },
  { id: 4, action: 'New user registered', user: 'System', time: '1h ago', type: 'user' },
  { id: 5, action: 'Incident type updated', user: 'Juan Dela Cruz', time: '2h ago', type: 'resolve' },
  { id: 6, action: 'Report RPT010 marked invalid', user: 'Maria Santos', time: '3h ago', type: 'resolve' },
];

export const mockAdminReports: AdminReport[] = [
  {
    id: 'AR001',
    reportId: 'RPT001',
    timestamp: '2026-03-04T06:30:00Z',
    status: 'pending',
    priority: 'high',
    incidentType: 'Disaster',
    assignedTeam: 'TM001',
    driver: {
      driverName: 'Roberto Guzman',
      governmentCardPlateNo: 'DL-2024-0089 / ABX 1234',
      authorizedPassenger: 'Santiago Perez',
      placeVisitedInspected: 'Barangay Poblacion, Dagupan',
      purpose: 'Flood rescue and evacuation',
      gasoline: { balanceInTank: '15', issuedByOffice: '20', asPurchased: '0', deductUsed: '12', balanceEndTrip: '23' },
      passengerName: 'Santiago Perez',
      driverFilledName: 'Roberto Guzman',
    },
    emergency: {
      timeReported: '06:30 AM',
      timeOfArrival: '06:52 AM',
      date: '2026-03-04',
      location: 'Barangay Poblacion, Dagupan',
      patientName: 'Multiple residents',
      age: 'Various',
      sex: 'Male',
      address: 'Rizal Street, Poblacion, Dagupan',
      typeOfIncident: 'Others',
      allergies: 'N/K',
      medications: 'N/K',
      assessmentComment: 'Knee-deep flooding reported along Rizal Street. Several families trapped in their homes.',
      treatmentManagement: 'Evacuation in progress. Residents relocated to barangay hall.',
      vitalSigns: { bloodPressure: '120/80', pulseRate: '78', respiration: '18' },
      endorsedBy: 'Maria Santos',
      endorsedByTime: '06:35 AM',
      endorsedByDate: '2026-03-04',
      endorsedTo: 'Roberto Guzman',
      endorsedToTime: '06:40 AM',
      endorsedToDate: '2026-03-04',
    },
  },
  {
    id: 'AR002',
    reportId: 'RPT002',
    timestamp: '2026-03-04T07:15:00Z',
    status: 'dispatched',
    priority: 'critical',
    incidentType: 'Fire',
    assignedTeam: 'TM001',
    driver: {
      driverName: 'Roberto Guzman',
      governmentCardPlateNo: 'DL-2024-0089 / ABX 1234',
      authorizedPassenger: 'Santiago Perez, Andres Bautista',
      placeVisitedInspected: 'Barangay Tapuac, Dagupan',
      purpose: 'Fire response and suppression',
      gasoline: { balanceInTank: '23', issuedByOffice: '10', asPurchased: '5', deductUsed: '18', balanceEndTrip: '20' },
      passengerName: 'Santiago Perez',
      driverFilledName: 'Roberto Guzman',
    },
    emergency: {
      timeReported: '07:15 AM',
      timeOfArrival: '07:28 AM',
      date: '2026-03-04',
      location: 'Barangay Tapuac, Dagupan',
      patientName: 'N/A — Property incident',
      age: 'N/A',
      sex: 'Male',
      address: 'Mabini Avenue, Tapuac, Dagupan',
      typeOfIncident: 'Others',
      allergies: 'N/A',
      medications: 'N/A',
      assessmentComment: 'House fire at Mabini Avenue. Smoke visible from several blocks away.',
      treatmentManagement: 'Fire suppression in progress. Perimeter secured. No casualties reported.',
      vitalSigns: { bloodPressure: 'N/A', pulseRate: 'N/A', respiration: 'N/A' },
      endorsedBy: 'Maria Santos',
      endorsedByTime: '07:18 AM',
      endorsedByDate: '2026-03-04',
      endorsedTo: 'Roberto Guzman',
      endorsedToTime: '07:20 AM',
      endorsedToDate: '2026-03-04',
    },
  },
  {
    id: 'AR003',
    reportId: 'RPT003',
    timestamp: '2026-03-04T08:45:00Z',
    status: 'acknowledged',
    priority: 'medium',
    incidentType: 'Vehicular',
    assignedTeam: 'TM002',
    driver: {
      driverName: 'Carmen Rivera',
      governmentCardPlateNo: 'DL-2024-0112 / CDF 5678',
      authorizedPassenger: 'Teresa Flores',
      placeVisitedInspected: 'Quezon Boulevard, Dagupan',
      purpose: 'Vehicular accident response',
      gasoline: { balanceInTank: '18', issuedByOffice: '15', asPurchased: '0', deductUsed: '8', balanceEndTrip: '25' },
      passengerName: 'Teresa Flores',
      driverFilledName: 'Carmen Rivera',
    },
    emergency: {
      timeReported: '08:45 AM',
      timeOfArrival: '08:58 AM',
      date: '2026-03-04',
      location: 'Quezon Boulevard, Dagupan',
      patientName: 'Jose Magbanua',
      age: '45',
      sex: 'Male',
      address: 'Quezon Blvd, Dagupan',
      typeOfIncident: 'Vehicular Accident',
      allergies: 'Penicillin',
      medications: 'Amlodipine 5mg',
      assessmentComment: 'Two-vehicle collision at intersection. Driver has lacerations on forehead.',
      treatmentManagement: 'Wound cleaning and dressing applied. Patient advised for hospital transfer.',
      vitalSigns: { bloodPressure: '140/90', pulseRate: '95', respiration: '22' },
      endorsedBy: 'Pedro Reyes',
      endorsedByTime: '08:48 AM',
      endorsedByDate: '2026-03-04',
      endorsedTo: 'Carmen Rivera',
      endorsedToTime: '08:50 AM',
      endorsedToDate: '2026-03-04',
    },
  },
  {
    id: 'AR004',
    reportId: 'RPT004',
    timestamp: '2026-03-04T09:20:00Z',
    status: 'resolved',
    priority: 'high',
    incidentType: 'Medical Emergency',
    assignedTeam: 'TM002',
    driver: {
      driverName: 'Carmen Rivera',
      governmentCardPlateNo: 'DL-2024-0112 / CDF 5678',
      authorizedPassenger: 'Teresa Flores',
      placeVisitedInspected: 'Barangay Bonuan, Dagupan',
      purpose: 'Medical emergency response — chest pain',
      gasoline: { balanceInTank: '25', issuedByOffice: '0', asPurchased: '10', deductUsed: '14', balanceEndTrip: '21' },
      passengerName: 'Teresa Flores',
      driverFilledName: 'Carmen Rivera',
    },
    emergency: {
      timeReported: '09:20 AM',
      timeOfArrival: '09:35 AM',
      date: '2026-03-04',
      location: 'Barangay Bonuan, Dagupan',
      patientName: 'Lourdes Villanueva',
      age: '72',
      sex: 'Female',
      address: '789 Bonuan, Dagupan',
      typeOfIncident: 'Medical',
      allergies: 'Aspirin, Sulfa drugs',
      medications: 'Metformin, Lisinopril',
      assessmentComment: 'Elderly resident experiencing chest pain. History of hypertension and diabetes.',
      treatmentManagement: 'Given sublingual NTG. Vital signs stabilized. Transported to Region 1 Medical Center.',
      vitalSigns: { bloodPressure: '160/100', pulseRate: '102', respiration: '24' },
      endorsedBy: 'Rafael Navarro',
      endorsedByTime: '09:22 AM',
      endorsedByDate: '2026-03-04',
      endorsedTo: 'Carmen Rivera',
      endorsedToTime: '09:25 AM',
      endorsedToDate: '2026-03-04',
    },
  },
  {
    id: 'AR005',
    reportId: 'RPT005',
    timestamp: '2026-03-03T14:00:00Z',
    status: 'dispatched',
    priority: 'high',
    incidentType: 'Disaster',
    assignedTeam: 'TM001',
    driver: {
      driverName: 'Roberto Guzman',
      governmentCardPlateNo: 'DL-2024-0089 / ABX 1234',
      authorizedPassenger: 'Santiago Perez, Diego Castillo',
      placeVisitedInspected: 'Dagupan City Proper',
      purpose: 'Typhoon response and monitoring',
      gasoline: { balanceInTank: '10', issuedByOffice: '30', asPurchased: '0', deductUsed: '22', balanceEndTrip: '18' },
      passengerName: 'Santiago Perez',
      driverFilledName: 'Roberto Guzman',
    },
    emergency: {
      timeReported: '02:00 PM',
      timeOfArrival: '02:18 PM',
      date: '2026-03-03',
      location: 'Dagupan City Proper',
      patientName: 'N/A — Area monitoring',
      age: 'N/A',
      sex: 'Male',
      address: 'Dagupan City Center',
      typeOfIncident: 'Others',
      allergies: 'N/A',
      medications: 'N/A',
      assessmentComment: 'Typhoon signal raised. Strong winds and heavy rainfall expected.',
      treatmentManagement: 'Pre-emptive evacuation advisory issued. Monitoring stations activated.',
      vitalSigns: { bloodPressure: 'N/A', pulseRate: 'N/A', respiration: 'N/A' },
      endorsedBy: 'Juan Dela Cruz',
      endorsedByTime: '02:05 PM',
      endorsedByDate: '2026-03-03',
      endorsedTo: 'Roberto Guzman',
      endorsedToTime: '02:08 PM',
      endorsedToDate: '2026-03-03',
    },
  },
  {
    id: 'AR006',
    reportId: 'RPT006',
    timestamp: '2026-03-03T16:30:00Z',
    status: 'pending',
    priority: 'medium',
    incidentType: 'Trauma',
    driver: {
      driverName: 'Antonio Reyes',
      governmentCardPlateNo: 'DL-2024-0156 / GHI 9012',
      authorizedPassenger: 'Francisco Diaz',
      placeVisitedInspected: 'Barangay Salapingao, Dagupan',
      purpose: 'Landslide assessment and road clearing',
      gasoline: { balanceInTank: '20', issuedByOffice: '10', asPurchased: '0', deductUsed: '6', balanceEndTrip: '24' },
      passengerName: 'Francisco Diaz',
      driverFilledName: 'Antonio Reyes',
    },
    emergency: {
      timeReported: '04:30 PM',
      timeOfArrival: '04:48 PM',
      date: '2026-03-03',
      location: 'Barangay Salapingao, Dagupan',
      patientName: 'N/A — Infrastructure incident',
      age: 'N/A',
      sex: 'Male',
      address: 'Del Pilar St, Salapingao, Dagupan',
      typeOfIncident: 'Others',
      allergies: 'N/A',
      medications: 'N/A',
      assessmentComment: 'Minor landslide blocking road access. No casualties reported.',
      treatmentManagement: 'Road clearing in progress. Barricades installed.',
      vitalSigns: { bloodPressure: 'N/A', pulseRate: 'N/A', respiration: 'N/A' },
      endorsedBy: 'Rosa Lim',
      endorsedByTime: '04:33 PM',
      endorsedByDate: '2026-03-03',
      endorsedTo: 'Antonio Reyes',
      endorsedToTime: '04:38 PM',
      endorsedToDate: '2026-03-03',
    },
  },
  {
    id: 'AR007',
    reportId: 'RPT007',
    timestamp: '2026-03-03T20:00:00Z',
    status: 'resolved',
    priority: 'low',
    incidentType: 'Service',
    assignedTeam: 'TM003',
    driver: {
      driverName: 'Antonio Reyes',
      governmentCardPlateNo: 'DL-2024-0156 / GHI 9012',
      authorizedPassenger: 'Francisco Diaz',
      placeVisitedInspected: 'Barangay Mayombo, Dagupan',
      purpose: 'Power outage inspection',
      gasoline: { balanceInTank: '24', issuedByOffice: '0', asPurchased: '5', deductUsed: '10', balanceEndTrip: '19' },
      passengerName: 'Francisco Diaz',
      driverFilledName: 'Antonio Reyes',
    },
    emergency: {
      timeReported: '08:00 PM',
      timeOfArrival: '08:22 PM',
      date: '2026-03-03',
      location: 'Barangay Mayombo, Dagupan',
      patientName: 'N/A — Utility incident',
      age: 'N/A',
      sex: 'Male',
      address: 'Burgos Ave, Mayombo, Dagupan',
      typeOfIncident: 'Others',
      allergies: 'N/A',
      medications: 'N/A',
      assessmentComment: 'Widespread power outage affecting entire barangay since 7PM.',
      treatmentManagement: 'Coordinated with DLEC. Power restored at 10:15 PM.',
      vitalSigns: { bloodPressure: 'N/A', pulseRate: 'N/A', respiration: 'N/A' },
      endorsedBy: 'Lourdes Villanueva',
      endorsedByTime: '08:03 PM',
      endorsedByDate: '2026-03-03',
      endorsedTo: 'Antonio Reyes',
      endorsedToTime: '08:08 PM',
      endorsedToDate: '2026-03-03',
    },
  },
  {
    id: 'AR008',
    reportId: 'RPT008',
    timestamp: '2026-03-04T11:00:00Z',
    status: 'pending',
    priority: 'low',
    incidentType: 'Service',
    driver: {
      driverName: 'Roberto Guzman',
      governmentCardPlateNo: 'DL-2024-0089 / ABX 1234',
      authorizedPassenger: 'Santiago Perez',
      placeVisitedInspected: 'Bonuan Beach, Dagupan',
      purpose: 'Water rescue and ambulance transport',
      gasoline: { balanceInTank: '18', issuedByOffice: '15', asPurchased: '0', deductUsed: '10', balanceEndTrip: '23' },
      passengerName: 'Santiago Perez',
      driverFilledName: 'Roberto Guzman',
    },
    emergency: {
      timeReported: '11:00 AM',
      timeOfArrival: '11:15 AM',
      date: '2026-03-04',
      location: 'Bonuan Beach, Dagupan',
      patientName: 'Unnamed male',
      age: '28',
      sex: 'Male',
      address: 'Bonuan Beach area, Dagupan',
      typeOfIncident: 'Medical',
      allergies: 'None known',
      medications: 'None',
      assessmentComment: 'Person swept away by strong currents at Bonuan Beach. Near-drowning.',
      treatmentManagement: 'CPR administered on scene. Patient conscious and breathing. Transported to hospital.',
      vitalSigns: { bloodPressure: '110/70', pulseRate: '110', respiration: '28' },
      endorsedBy: 'Fernando Aquino',
      endorsedByTime: '11:03 AM',
      endorsedByDate: '2026-03-04',
      endorsedTo: 'Roberto Guzman',
      endorsedToTime: '11:06 AM',
      endorsedToDate: '2026-03-04',
    },
  },
  {
    id: 'AR009',
    reportId: 'RPT009',
    timestamp: '2026-03-04T05:00:00Z',
    status: 'acknowledged',
    priority: 'high',
    incidentType: 'Disaster',
    assignedTeam: 'TM001',
    driver: {
      driverName: 'Roberto Guzman',
      governmentCardPlateNo: 'DL-2024-0089 / ABX 1234',
      authorizedPassenger: 'Santiago Perez',
      placeVisitedInspected: 'Barangay Pantal, Dagupan',
      purpose: 'Flood evacuation and rescue',
      gasoline: { balanceInTank: '12', issuedByOffice: '20', asPurchased: '0', deductUsed: '15', balanceEndTrip: '17' },
      passengerName: 'Santiago Perez',
      driverFilledName: 'Roberto Guzman',
    },
    emergency: {
      timeReported: '05:00 AM',
      timeOfArrival: '05:20 AM',
      date: '2026-03-04',
      location: 'Barangay Pantal, Dagupan',
      patientName: 'Multiple families',
      age: 'Various',
      sex: 'Female',
      address: 'Luna St, Pantal, Dagupan',
      typeOfIncident: 'Others',
      allergies: 'N/K',
      medications: 'N/K',
      assessmentComment: 'Waist-deep flood waters in Pantal area. Residents need evacuation.',
      treatmentManagement: 'Evacuation ongoing. 12 families relocated to evacuation center.',
      vitalSigns: { bloodPressure: 'N/A', pulseRate: 'N/A', respiration: 'N/A' },
      endorsedBy: 'Ana Garcia',
      endorsedByTime: '05:05 AM',
      endorsedByDate: '2026-03-04',
      endorsedTo: 'Roberto Guzman',
      endorsedToTime: '05:08 AM',
      endorsedToDate: '2026-03-04',
    },
  },
  {
    id: 'AR010',
    reportId: 'RPT010',
    timestamp: '2026-03-04T12:30:00Z',
    status: 'invalid',
    priority: 'medium',
    incidentType: 'Trauma',
    driver: {
      driverName: 'Carmen Rivera',
      governmentCardPlateNo: 'DL-2024-0112 / CDF 5678',
      authorizedPassenger: 'Teresa Flores',
      placeVisitedInspected: 'Barangay Carael, Dagupan',
      purpose: 'Structural inspection — reported leaning building',
      gasoline: { balanceInTank: '21', issuedByOffice: '0', asPurchased: '0', deductUsed: '5', balanceEndTrip: '16' },
      passengerName: 'Teresa Flores',
      driverFilledName: 'Carmen Rivera',
    },
    emergency: {
      timeReported: '12:30 PM',
      timeOfArrival: '12:45 PM',
      date: '2026-03-04',
      location: 'Barangay Carael, Dagupan',
      patientName: 'N/A — Structural report',
      age: 'N/A',
      sex: 'Male',
      address: 'Magsaysay St, Carael, Dagupan',
      typeOfIncident: 'Others',
      allergies: 'N/A',
      medications: 'N/A',
      assessmentComment: 'Report of building leaning. Upon inspection, building is stable but needs repair.',
      treatmentManagement: 'Marked as invalid. Referred to City Engineering for assessment.',
      vitalSigns: { bloodPressure: 'N/A', pulseRate: 'N/A', respiration: 'N/A' },
      endorsedBy: 'Isabella Ramos',
      endorsedByTime: '12:33 PM',
      endorsedByDate: '2026-03-04',
      endorsedTo: 'Carmen Rivera',
      endorsedToTime: '12:36 PM',
      endorsedToDate: '2026-03-04',
    },
  },
  {
    id: 'AR011',
    reportId: 'RPT011',
    timestamp: '2026-03-04T13:45:00Z',
    status: 'pending',
    priority: 'critical',
    incidentType: 'Fire',
    driver: {
      driverName: 'Antonio Reyes',
      governmentCardPlateNo: 'DL-2024-0156 / GHI 9012',
      authorizedPassenger: 'Francisco Diaz',
      placeVisitedInspected: 'Barangay Poblacion, Dagupan',
      purpose: 'Grass fire response',
      gasoline: { balanceInTank: '19', issuedByOffice: '15', asPurchased: '0', deductUsed: '8', balanceEndTrip: '26' },
      passengerName: 'Francisco Diaz',
      driverFilledName: 'Antonio Reyes',
    },
    emergency: {
      timeReported: '01:45 PM',
      timeOfArrival: '01:58 PM',
      date: '2026-03-04',
      location: 'Barangay Poblacion, Dagupan',
      patientName: 'N/A — Fire incident',
      age: 'N/A',
      sex: 'Male',
      address: 'Rizal Ave, Poblacion, Dagupan',
      typeOfIncident: 'Others',
      allergies: 'N/A',
      medications: 'N/A',
      assessmentComment: 'Grass fire near residential area spreading quickly due to wind.',
      treatmentManagement: 'Fire suppression in progress. Fire line established.',
      vitalSigns: { bloodPressure: 'N/A', pulseRate: 'N/A', respiration: 'N/A' },
      endorsedBy: 'Pedro Reyes',
      endorsedByTime: '01:48 PM',
      endorsedByDate: '2026-03-04',
      endorsedTo: 'Antonio Reyes',
      endorsedToTime: '01:50 PM',
      endorsedToDate: '2026-03-04',
    },
  },
  {
    id: 'AR012',
    reportId: 'RPT012',
    timestamp: '2026-03-04T02:00:00Z',
    status: 'resolved',
    priority: 'high',
    incidentType: 'Disaster',
    assignedTeam: 'TM001',
    driver: {
      driverName: 'Roberto Guzman',
      governmentCardPlateNo: 'DL-2024-0089 / ABX 1234',
      authorizedPassenger: 'Santiago Perez, Andres Bautista',
      placeVisitedInspected: 'Dagupan City',
      purpose: 'Earthquake response and structural assessment',
      gasoline: { balanceInTank: '17', issuedByOffice: '25', asPurchased: '0', deductUsed: '20', balanceEndTrip: '22' },
      passengerName: 'Santiago Perez',
      driverFilledName: 'Roberto Guzman',
    },
    emergency: {
      timeReported: '02:00 AM',
      timeOfArrival: '02:25 AM',
      date: '2026-03-04',
      location: 'Dagupan City',
      patientName: 'Multiple residents',
      age: 'Various',
      sex: 'Male',
      address: 'Dagupan City Center',
      typeOfIncident: 'Others',
      allergies: 'N/K',
      medications: 'N/K',
      assessmentComment: 'Magnitude 4.5 earthquake felt. Minor damage to structures reported.',
      treatmentManagement: 'Structural assessment completed. No critical damage. Advisory cleared at 4:00 AM.',
      vitalSigns: { bloodPressure: 'N/A', pulseRate: 'N/A', respiration: 'N/A' },
      endorsedBy: 'Juan Dela Cruz',
      endorsedByTime: '02:05 AM',
      endorsedByDate: '2026-03-04',
      endorsedTo: 'Roberto Guzman',
      endorsedToTime: '02:10 AM',
      endorsedToDate: '2026-03-04',
    },
  },
];
